"""execution_session_binding"""

import sqlalchemy as sa
from alembic import op

revision = "f9eb2d12038e"
down_revision = "fbaa934e5022"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agents", sa.Column("session_id", sa.String(length=36), nullable=True))
    op.add_column("commands", sa.Column("delivery_session_id", sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("commands", "delivery_session_id")
    op.drop_column("agents", "session_id")
    # ### end Alembic commands ###
