"""rate_bucket_retention"""

import sqlalchemy as sa
from alembic import op

revision = "fbaa934e5022"
down_revision = "a49bdbd777b8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rate_buckets", sa.Column("updated_at", sa.BigInteger(), nullable=False, server_default="0")
    )
    op.alter_column("rate_buckets", "updated_at", server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rate_buckets", "updated_at")
    # ### end Alembic commands ###
